spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ats_database
    username: ats_user
    password: ats_super_secreto_123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
# Configuración de Inteligencia Artificial (Gemini)
gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"

# Configuración de los Tokens JWT
jwt:
  secret: "AtsApi_SuperSecreta_Clave_Para_Firmar_Tokens_2026_!@#"